"""empty message

Revision ID: 6b3d4916c3dd
Revises: c78fbb8951f9
Create Date: 2021-01-29 14:44:00.984092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b3d4916c3dd'
down_revision = 'c78fbb8951f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'body',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'body',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
