"""add is_complete field.

Revision ID: 85496f7669bf
Revises: cd576ed84b9e
Create Date: 2021-02-01 16:20:48.382560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85496f7669bf'
down_revision = 'cd576ed84b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'is_complete')
    # ### end Alembic commands ###
