"""Update todo table.

Revision ID: c78fbb8951f9
Revises: 1d5bf9804949
Create Date: 2021-01-29 11:37:46.432620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78fbb8951f9'
down_revision = '1d5bf9804949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'created_at')
    # ### end Alembic commands ###
